language: node_js

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f services/kafka/docker-compose.yml up -d

script:
  - npm run lint
  - npm run test

node_js:
  - 13
  - node
